[package]
name = "LinearFitSearch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.4"
once_cell = "1.10.0"
rand = "0.8"
colored = "2.0"
